kind = "web"
previewPath = "/"
title = "Waslney"
version = "1.0.0"
id = "artifacts/waslney"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22593

[services.development]
run = "pnpm --filter @workspace/waslney run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/waslney", "run", "build" ]
publicDir = "artifacts/waslney/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22593"
BASE_PATH = "/"
